# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in yaruo.gemspec
gemspec

gem "activesupport"

gem "minitest", "~> 5.16"

gem "rake", "~> 13.0"

gem "thor"
